"""create_all_28_tables

Revision ID: fadc48ff1682
Revises: 
Create Date: 2026-08-11 15:14:11.631464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fadc48ff1682'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'UPLOAD', 'IMPORT', 'UPDATE', 'DELETE', 'MATCH', 'VALIDATION', 'CALCULATION', 'ADJUSTMENT', 'APPROVAL', 'REJECTION', 'PAYMENT', 'EXPORT', name='audit_action_enum'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('candidate_data_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_data_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_data_versions_division'), ['division'], unique=False)

    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_division_org_code')
    )
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_divisions_code'), ['code'], unique=False)

    op.create_table('hours_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('benchmark_hours', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hours_benchmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hours_benchmarks_division'), ['division'], unique=True)

    op.create_table('hours_data_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hours_data_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hours_data_versions_division'), ['division'], unique=False)

    op.create_table('incentive_slabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('slab_type', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('margin_min', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('margin_max', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('hours_min', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('hours_max', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incentive_slabs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incentive_slabs_division'), ['division'], unique=False)
        batch_op.create_index(batch_op.f('ix_incentive_slabs_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_incentive_slabs_slab_type'), ['slab_type'], unique=False)

    op.create_table('project_end_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_end_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_end_versions_division'), ['division'], unique=False)

    op.create_table('recruiter_master_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recruiter_master_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruiter_master_versions_division'), ['division'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_candidate_id', sa.String(length=100), nullable=False),
    sa.Column('start_id', sa.String(length=100), nullable=True),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('normalized_client', sa.String(length=255), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('pay_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('bill_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('margin', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('recruiter', sa.String(length=255), nullable=True),
    sa.Column('team_lead', sa.String(length=255), nullable=True),
    sa.Column('manager', sa.String(length=255), nullable=True),
    sa.Column('senior_manager', sa.String(length=255), nullable=True),
    sa.Column('crm', sa.String(length=255), nullable=True),
    sa.Column('associate_director', sa.String(length=255), nullable=True),
    sa.Column('center_head', sa.String(length=255), nullable=True),
    sa.Column('avp', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('candidate_source', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('source_version_id', sa.Integer(), nullable=False),
    sa.Column('last_touched_version_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['last_touched_version_id'], ['candidate_data_versions.id'], ),
    sa.ForeignKeyConstraint(['source_version_id'], ['candidate_data_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_client'), ['client'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_division'), ['division'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_external_candidate_id'), ['external_candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_normalized_client'), ['normalized_client'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_start_id'), ['start_id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('employee_code', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role_title', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_employee_code'), ['employee_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('incentive_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('incentive_month', sa.String(length=7), nullable=False),
    sa.Column('cycle_start_date', sa.Date(), nullable=True),
    sa.Column('cycle_end_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'MATCHED', 'VALIDATED', 'CALCULATED', 'APPROVED', 'PAID', 'CLOSED', name='cycle_status_enum'), nullable=False),
    sa.Column('candidate_version_id', sa.Integer(), nullable=True),
    sa.Column('recruiter_version_id', sa.Integer(), nullable=True),
    sa.Column('hours_version_id', sa.Integer(), nullable=True),
    sa.Column('project_end_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_version_id'], ['candidate_data_versions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hours_version_id'], ['hours_data_versions.id'], ),
    sa.ForeignKeyConstraint(['project_end_version_id'], ['project_end_versions.id'], ),
    sa.ForeignKeyConstraint(['recruiter_version_id'], ['recruiter_master_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incentive_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incentive_cycles_division'), ['division'], unique=False)
        batch_op.create_index(batch_op.f('ix_incentive_cycles_incentive_month'), ['incentive_month'], unique=False)

    op.create_table('cycle_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('checked_by', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['incentive_cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'item_key', name='uq_cycle_checklist_key')
    )
    with op.batch_alter_table('cycle_checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_checklist_items_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('cycle_data_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['incentive_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_data_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_data_snapshots_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('cycle_hours_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('source_row_ref', sa.String(length=100), nullable=True),
    sa.Column('source_candidate_name', sa.String(length=255), nullable=True),
    sa.Column('source_candidate_id', sa.String(length=100), nullable=True),
    sa.Column('source_client', sa.String(length=255), nullable=True),
    sa.Column('hours_worked', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('match_method', sa.String(length=50), nullable=True),
    sa.Column('match_result', sa.Enum('MATCHED', 'UNMATCHED', 'LOW_CONFIDENCE', 'DUPLICATE', 'MANUAL', 'REJECTED', name='match_result_enum'), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['incentive_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_hours_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_hours_matches_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('cycle_manual_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('candidate_name', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('person', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['incentive_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_manual_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_manual_adjustments_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('cycle_payment_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['incentive_cycles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'candidate_id', name='uq_cycle_payment_candidate')
    )
    with op.batch_alter_table('cycle_payment_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_payment_statuses_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('cycle_validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('check_key', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['incentive_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_validation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_validation_results_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('hours_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=True),
    sa.Column('month_key', sa.String(length=7), nullable=True),
    sa.Column('hours_worked', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('raw_candidate_name', sa.String(length=255), nullable=True),
    sa.Column('match_method', sa.String(length=50), nullable=True),
    sa.Column('match_confidence', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['hours_data_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hours_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hours_rows_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hours_rows_month_key'), ['month_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_hours_rows_version_id'), ['version_id'], unique=False)

    op.create_table('incentive_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('candidate_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('person', sa.String(length=255), nullable=False),
    sa.Column('incentive_type', sa.String(length=50), nullable=False),
    sa.Column('rule_applied', sa.String(length=255), nullable=True),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('base_incentive', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pro_rata_factor', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('hours', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('margin', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('explanation_json', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['incentive_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incentive_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incentive_lines_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incentive_lines_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('project_end_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('project_end_date', sa.Date(), nullable=True),
    sa.Column('project_end', sa.Boolean(), nullable=False),
    sa.Column('project_end_source', sa.String(length=100), nullable=True),
    sa.Column('hours_before_project_end', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('eligibility_flag', sa.String(length=100), nullable=True),
    sa.Column('raw_candidate_name', sa.String(length=255), nullable=True),
    sa.Column('match_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['project_end_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_end_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_end_records_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_end_records_version_id'), ['version_id'], unique=False)

    op.create_table('recruiter_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('recruiter_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LEFT', 'NOTICE', name='recruiter_status_enum'), nullable=False),
    sa.Column('effective_month', sa.String(length=7), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['recruiter_master_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'employee_id', 'effective_month', name='uq_recruiter_status_version_emp_month')
    )
    with op.batch_alter_table('recruiter_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruiter_statuses_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruiter_statuses_version_id'), ['version_id'], unique=False)

    op.create_table('incentive_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incentive_line_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incentive_line_id'], ['incentive_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incentive_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incentive_approvals_incentive_line_id'), ['incentive_line_id'], unique=False)

    op.create_table('incentive_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incentive_line_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incentive_line_id'], ['incentive_lines.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incentive_line_id', name='uq_incentive_payment_line')
    )
    with op.batch_alter_table('incentive_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incentive_payments_incentive_line_id'), ['incentive_line_id'], unique=False)

    op.create_table('paid_incentive_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('person', sa.String(length=255), nullable=False),
    sa.Column('incentive_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['incentive_cycles.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['incentive_payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_paid_ledger_dedupe_key')
    )
    with op.batch_alter_table('paid_incentive_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paid_incentive_ledger_payment_id'), ['payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paid_incentive_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paid_incentive_ledger_payment_id'))

    op.drop_table('paid_incentive_ledger')
    with op.batch_alter_table('incentive_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incentive_payments_incentive_line_id'))

    op.drop_table('incentive_payments')
    with op.batch_alter_table('incentive_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incentive_approvals_incentive_line_id'))

    op.drop_table('incentive_approvals')
    with op.batch_alter_table('recruiter_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruiter_statuses_version_id'))
        batch_op.drop_index(batch_op.f('ix_recruiter_statuses_normalized_name'))

    op.drop_table('recruiter_statuses')
    with op.batch_alter_table('project_end_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_end_records_version_id'))
        batch_op.drop_index(batch_op.f('ix_project_end_records_candidate_id'))

    op.drop_table('project_end_records')
    with op.batch_alter_table('incentive_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incentive_lines_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_incentive_lines_candidate_id'))

    op.drop_table('incentive_lines')
    with op.batch_alter_table('hours_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hours_rows_version_id'))
        batch_op.drop_index(batch_op.f('ix_hours_rows_month_key'))
        batch_op.drop_index(batch_op.f('ix_hours_rows_candidate_id'))

    op.drop_table('hours_rows')
    with op.batch_alter_table('cycle_validation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_validation_results_cycle_id'))

    op.drop_table('cycle_validation_results')
    with op.batch_alter_table('cycle_payment_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_payment_statuses_cycle_id'))

    op.drop_table('cycle_payment_statuses')
    with op.batch_alter_table('cycle_manual_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_manual_adjustments_cycle_id'))

    op.drop_table('cycle_manual_adjustments')
    with op.batch_alter_table('cycle_hours_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_hours_matches_cycle_id'))

    op.drop_table('cycle_hours_matches')
    with op.batch_alter_table('cycle_data_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_data_snapshots_cycle_id'))

    op.drop_table('cycle_data_snapshots')
    with op.batch_alter_table('cycle_checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_checklist_items_cycle_id'))

    op.drop_table('cycle_checklist_items')
    with op.batch_alter_table('incentive_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incentive_cycles_incentive_month'))
        batch_op.drop_index(batch_op.f('ix_incentive_cycles_division'))

    op.drop_table('incentive_cycles')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_code'))

    op.drop_table('employees')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_start_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_candidates_normalized_client'))
        batch_op.drop_index(batch_op.f('ix_candidates_external_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_division'))
        batch_op.drop_index(batch_op.f('ix_candidates_client'))

    op.drop_table('candidates')
    op.drop_table('user_roles')
    with op.batch_alter_table('recruiter_master_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruiter_master_versions_division'))

    op.drop_table('recruiter_master_versions')
    with op.batch_alter_table('project_end_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_end_versions_division'))

    op.drop_table('project_end_versions')
    with op.batch_alter_table('incentive_slabs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incentive_slabs_slab_type'))
        batch_op.drop_index(batch_op.f('ix_incentive_slabs_role'))
        batch_op.drop_index(batch_op.f('ix_incentive_slabs_division'))

    op.drop_table('incentive_slabs')
    with op.batch_alter_table('hours_data_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hours_data_versions_division'))

    op.drop_table('hours_data_versions')
    with op.batch_alter_table('hours_benchmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hours_benchmarks_division'))

    op.drop_table('hours_benchmarks')
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_divisions_code'))

    op.drop_table('divisions')
    with op.batch_alter_table('candidate_data_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_data_versions_division'))

    op.drop_table('candidate_data_versions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    op.drop_table('organizations')
    # ### end Alembic commands ###
