from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

# Records imported from Incentive_Report_Converted_All.xlsx
RECORDS = [   {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-2001',
        'candidate_name': 'Emma Kapoor',
        'start_date': '2026-07-09',
        'month': '2026-07-01',
        'contract_type': 'W2',
        'margin': 8.3,
        'hours': 160.0,
        'incentive_amount': 4200,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Internal DB',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Natalie Pereira',
        'coordinator_type': 'CRM',
        'candidate_id': 'CAND-NSK-2002',
        'candidate_name': 'Maya Patel',
        'start_date': '2026-01-08',
        'month': '2026-06-01',
        'contract_type': 'W2',
        'margin': 8.5,
        'hours': 152.0,
        'incentive_amount': 4200,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Vendor',
        'team': 'Nashik CRM'},
    {   'coordinator_name': 'Neha Sharma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-2003',
        'candidate_name': 'Ryan Saxena',
        'start_date': '2026-03-13',
        'month': '2026-06-01',
        'contract_type': 'W2',
        'margin': 15.5,
        'hours': 128.0,
        'incentive_amount': 2500,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Internal DB',
        'team': 'Nashik Team Bravo'},
    {   'coordinator_name': 'Rohan Verma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-2004',
        'candidate_name': 'Kabir Nair',
        'start_date': '2026-04-02',
        'month': '2026-07-01',
        'contract_type': 'FULLTIME',
        'margin': 7587.1,
        'hours': 1.0,
        'incentive_amount': 4000,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Internal DB',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Rohan Verma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-2005',
        'candidate_name': 'Kabir Fernandes',
        'start_date': '2026-05-22',
        'month': '2026-07-01',
        'contract_type': 'FULLTIME',
        'margin': 9711.1,
        'hours': 1.0,
        'incentive_amount': 1500,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Vendor',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Rohan Verma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-2006',
        'candidate_name': 'Sara Chatterjee',
        'start_date': '2026-07-17',
        'month': '2026-07-01',
        'contract_type': 'W2',
        'margin': 17.8,
        'hours': 96.0,
        'incentive_amount': 2500,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Vendor',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Karan Johar',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-2007',
        'candidate_name': 'Zoe Reddy',
        'start_date': '2026-06-21',
        'month': '2026-07-01',
        'contract_type': 'FULLTIME',
        'margin': 11619.9,
        'hours': 1.0,
        'incentive_amount': 1000,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'LinkedIn',
        'team': 'Nashik Team Charlie'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-2008',
        'candidate_name': 'Divya Iyer',
        'start_date': '2026-04-29',
        'month': '2026-07-01',
        'contract_type': 'C2C',
        'margin': 19.8,
        'hours': 160.0,
        'incentive_amount': 250,
        'incentive_type': 'RECURRING',
        'candidate_source': 'LinkedIn',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Rohan Verma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-2009',
        'candidate_name': 'Aarav Shetty',
        'start_date': '2026-03-10',
        'month': '2026-06-01',
        'contract_type': 'W2',
        'margin': 18.7,
        'hours': 152.0,
        'incentive_amount': 4000,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Vendor',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-2010',
        'candidate_name': "Ryan D'Souza",
        'start_date': '2026-03-09',
        'month': '2026-06-01',
        'contract_type': 'W2',
        'margin': 16.2,
        'hours': 152.0,
        'incentive_amount': 3500,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Internal DB',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Priya Singh',
        'coordinator_type': 'Team Lead',
        'candidate_id': 'CAND-NSK-2011',
        'candidate_name': 'Zoe Chatterjee',
        'start_date': '2026-02-05',
        'month': '2026-08-01',
        'contract_type': 'C2C',
        'margin': 6.4,
        'hours': 96.0,
        'incentive_amount': 1000,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Vendor',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Priya Singh',
        'coordinator_type': 'Team Lead',
        'candidate_id': 'CAND-NSK-2012',
        'candidate_name': 'Leah Fernandes',
        'start_date': '2026-04-09',
        'month': '2026-07-01',
        'contract_type': 'FULLTIME',
        'margin': 11976.7,
        'hours': 1.0,
        'incentive_amount': 4200,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'LinkedIn',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-2013',
        'candidate_name': 'Emma Chopra',
        'start_date': '2026-07-12',
        'month': '2026-07-01',
        'contract_type': 'FULLTIME',
        'margin': 8041.1,
        'hours': 1.0,
        'incentive_amount': 1000,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Naukri',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Rohan Verma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-2014',
        'candidate_name': 'Ethan Rao',
        'start_date': '2026-07-15',
        'month': '2026-06-01',
        'contract_type': 'FULLTIME',
        'margin': 11475.8,
        'hours': 1.0,
        'incentive_amount': 2000,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Internal DB',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Natalie Pereira',
        'coordinator_type': 'CRM',
        'candidate_id': 'CAND-NSK-2015',
        'candidate_name': 'Leah Reddy',
        'start_date': '2026-02-09',
        'month': '2026-07-01',
        'contract_type': 'W2',
        'margin': 13.1,
        'hours': 152.0,
        'incentive_amount': 4000,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Referral',
        'team': 'Nashik CRM'},
    {   'coordinator_name': 'Rohan Verma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-2016',
        'candidate_name': 'Zoe Menon',
        'start_date': '2026-03-03',
        'month': '2026-06-01',
        'contract_type': 'W2',
        'margin': 18.2,
        'hours': 96.0,
        'incentive_amount': 500,
        'incentive_type': 'RECURRING',
        'candidate_source': 'LinkedIn',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Neha Sharma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-2017',
        'candidate_name': 'Noah Gupta',
        'start_date': '2026-05-21',
        'month': '2026-06-01',
        'contract_type': 'C2C',
        'margin': 12.9,
        'hours': 152.0,
        'incentive_amount': 1500,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Naukri',
        'team': 'Nashik Team Bravo'},
    {   'coordinator_name': 'Karan Johar',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-2018',
        'candidate_name': 'Kabir Kulkarni',
        'start_date': '2026-04-23',
        'month': '2026-08-01',
        'contract_type': 'C2C',
        'margin': 6.8,
        'hours': 120.0,
        'incentive_amount': 4200,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Vendor',
        'team': 'Nashik Team Charlie'},
    {   'coordinator_name': 'Natalie Pereira',
        'coordinator_type': 'CRM',
        'candidate_id': 'CAND-NSK-2019',
        'candidate_name': 'Divya Kapoor',
        'start_date': '2026-01-19',
        'month': '2026-08-01',
        'contract_type': 'FULLTIME',
        'margin': 6353.2,
        'hours': 1.0,
        'incentive_amount': 2500,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Naukri',
        'team': 'Nashik CRM'},
    {   'coordinator_name': 'Natalie Pereira',
        'coordinator_type': 'CRM',
        'candidate_id': 'CAND-NSK-2020',
        'candidate_name': 'Divya Bose',
        'start_date': '2026-06-21',
        'month': '2026-07-01',
        'contract_type': 'W2',
        'margin': 13.1,
        'hours': 160.0,
        'incentive_amount': 3500,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Vendor',
        'team': 'Nashik CRM'},
    {   'coordinator_name': 'Rohan Verma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-3001',
        'candidate_name': 'Emma Roy',
        'start_date': '2026-04-01',
        'month': '2026-07-01',
        'contract_type': 'C2C',
        'margin': 12.0,
        'hours': 160.0,
        'incentive_amount': 500,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Internal DB',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Priya Singh',
        'coordinator_type': 'Team Lead',
        'candidate_id': 'CAND-NSK-3002',
        'candidate_name': 'Aarav Nair',
        'start_date': '2026-03-05',
        'month': '2026-06-01',
        'contract_type': 'W2',
        'margin': 13.0,
        'hours': 120.0,
        'incentive_amount': 4000,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Internal DB',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Rohan Verma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-3003',
        'candidate_name': 'Ryan Chopra',
        'start_date': '2026-01-26',
        'month': '2026-06-01',
        'contract_type': 'FULLTIME',
        'margin': 11995.7,
        'hours': 1.0,
        'incentive_amount': 500,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Vendor',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Neha Sharma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-3004',
        'candidate_name': 'Maya Gupta',
        'start_date': '2026-05-04',
        'month': '2026-06-01',
        'contract_type': 'C2C',
        'margin': 18.5,
        'hours': 120.0,
        'incentive_amount': 2000,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'LinkedIn',
        'team': 'Nashik Team Bravo'},
    {   'coordinator_name': 'Karan Johar',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-3005',
        'candidate_name': 'Maya Chopra',
        'start_date': '2026-06-19',
        'month': '2026-08-01',
        'contract_type': 'C2C',
        'margin': 7.3,
        'hours': 128.0,
        'incentive_amount': 4200,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Vendor',
        'team': 'Nashik Team Charlie'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-3006',
        'candidate_name': 'Aarav Patel',
        'start_date': '2026-01-13',
        'month': '2026-08-01',
        'contract_type': 'C2C',
        'margin': 12.5,
        'hours': 152.0,
        'incentive_amount': 500,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Naukri',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Rohan Verma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-3007',
        'candidate_name': 'Leah Fernandes',
        'start_date': '2026-06-22',
        'month': '2026-06-01',
        'contract_type': 'C2C',
        'margin': 6.8,
        'hours': 152.0,
        'incentive_amount': 250,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Vendor',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Rohan Verma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-3008',
        'candidate_name': 'Maya Saxena',
        'start_date': '2026-05-25',
        'month': '2026-08-01',
        'contract_type': 'C2C',
        'margin': 19.0,
        'hours': 120.0,
        'incentive_amount': 3500,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Naukri',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-3009',
        'candidate_name': 'Ava Bhatt',
        'start_date': '2026-03-22',
        'month': '2026-06-01',
        'contract_type': 'W2',
        'margin': 11.9,
        'hours': 152.0,
        'incentive_amount': 1500,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Naukri',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Karan Johar',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-3010',
        'candidate_name': 'Noah Kulkarni',
        'start_date': '2026-01-18',
        'month': '2026-06-01',
        'contract_type': 'C2C',
        'margin': 9.3,
        'hours': 144.0,
        'incentive_amount': 4200,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Naukri',
        'team': 'Nashik Team Charlie'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-3011',
        'candidate_name': 'Isla Menon',
        'start_date': '2026-06-19',
        'month': '2026-06-01',
        'contract_type': 'W2',
        'margin': 9.0,
        'hours': 96.0,
        'incentive_amount': 1500,
        'incentive_type': 'RECURRING',
        'candidate_source': 'LinkedIn',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Karan Johar',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-3012',
        'candidate_name': 'Rahul Bose',
        'start_date': '2026-05-10',
        'month': '2026-07-01',
        'contract_type': 'C2C',
        'margin': 18.6,
        'hours': 96.0,
        'incentive_amount': 2000,
        'incentive_type': 'RECURRING',
        'candidate_source': 'LinkedIn',
        'team': 'Nashik Team Charlie'},
    {   'coordinator_name': 'Rohan Verma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-3013',
        'candidate_name': "Aarav D'Souza",
        'start_date': '2026-06-13',
        'month': '2026-07-01',
        'contract_type': 'W2',
        'margin': 16.1,
        'hours': 152.0,
        'incentive_amount': 500,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Vendor',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-3014',
        'candidate_name': 'Noah Chopra',
        'start_date': '2026-01-10',
        'month': '2026-07-01',
        'contract_type': 'FULLTIME',
        'margin': 9315.2,
        'hours': 1.0,
        'incentive_amount': 250,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Naukri',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Karan Johar',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-3015',
        'candidate_name': 'Sara Kulkarni',
        'start_date': '2026-02-23',
        'month': '2026-08-01',
        'contract_type': 'W2',
        'margin': 15.0,
        'hours': 128.0,
        'incentive_amount': 1000,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Internal DB',
        'team': 'Nashik Team Charlie'},
    {   'coordinator_name': 'Neha Sharma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-3016',
        'candidate_name': 'Olivia Roy',
        'start_date': '2026-01-07',
        'month': '2026-06-01',
        'contract_type': 'FULLTIME',
        'margin': 11546.9,
        'hours': 1.0,
        'incentive_amount': 1500,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Referral',
        'team': 'Nashik Team Bravo'},
    {   'coordinator_name': 'Neha Sharma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-3017',
        'candidate_name': 'Emma Shetty',
        'start_date': '2026-01-10',
        'month': '2026-07-01',
        'contract_type': 'W2',
        'margin': 8.0,
        'hours': 144.0,
        'incentive_amount': 1500,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Internal DB',
        'team': 'Nashik Team Bravo'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-3018',
        'candidate_name': 'Rahul Shetty',
        'start_date': '2026-03-26',
        'month': '2026-07-01',
        'contract_type': 'W2',
        'margin': 19.5,
        'hours': 128.0,
        'incentive_amount': 3500,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Vendor',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Natalie Pereira',
        'coordinator_type': 'CRM',
        'candidate_id': 'CAND-NSK-3019',
        'candidate_name': 'Aarav Kapoor',
        'start_date': '2026-01-30',
        'month': '2026-07-01',
        'contract_type': 'W2',
        'margin': 13.7,
        'hours': 128.0,
        'incentive_amount': 3500,
        'incentive_type': 'RECURRING',
        'candidate_source': 'LinkedIn',
        'team': 'Nashik CRM'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-3020',
        'candidate_name': 'Aarav Roy',
        'start_date': '2026-06-05',
        'month': '2026-08-01',
        'contract_type': 'W2',
        'margin': 10.8,
        'hours': 152.0,
        'incentive_amount': 3500,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Vendor',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Natalie Pereira',
        'coordinator_type': 'CRM',
        'candidate_id': 'CAND-NSK-4001',
        'candidate_name': 'Isla Reddy',
        'start_date': '2026-04-04',
        'month': '2026-07-01',
        'contract_type': 'W2',
        'margin': 19.2,
        'hours': 128.0,
        'incentive_amount': 2000,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'LinkedIn',
        'team': 'Nashik CRM'},
    {   'coordinator_name': 'Karan Johar',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-4002',
        'candidate_name': 'Maya Malhotra',
        'start_date': '2026-04-14',
        'month': '2026-08-01',
        'contract_type': 'C2C',
        'margin': 13.3,
        'hours': 120.0,
        'incentive_amount': 1000,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Referral',
        'team': 'Nashik Team Charlie'},
    {   'coordinator_name': 'Natalie Pereira',
        'coordinator_type': 'CRM',
        'candidate_id': 'CAND-NSK-4003',
        'candidate_name': 'Ava Shetty',
        'start_date': '2026-05-21',
        'month': '2026-06-01',
        'contract_type': 'C2C',
        'margin': 9.3,
        'hours': 144.0,
        'incentive_amount': 4000,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Internal DB',
        'team': 'Nashik CRM'},
    {   'coordinator_name': 'Neha Sharma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-4004',
        'candidate_name': 'Vikram Gupta',
        'start_date': '2026-07-23',
        'month': '2026-08-01',
        'contract_type': 'W2',
        'margin': 14.9,
        'hours': 128.0,
        'incentive_amount': 2000,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Naukri',
        'team': 'Nashik Team Bravo'},
    {   'coordinator_name': 'Neha Sharma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-4005',
        'candidate_name': 'Noah Kapoor',
        'start_date': '2026-01-12',
        'month': '2026-06-01',
        'contract_type': 'C2C',
        'margin': 14.2,
        'hours': 96.0,
        'incentive_amount': 1500,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Naukri',
        'team': 'Nashik Team Bravo'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-4006',
        'candidate_name': 'Kabir Gupta',
        'start_date': '2026-04-13',
        'month': '2026-06-01',
        'contract_type': 'W2',
        'margin': 14.8,
        'hours': 96.0,
        'incentive_amount': 1500,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Internal DB',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-4007',
        'candidate_name': 'Vikram Bhatt',
        'start_date': '2026-01-13',
        'month': '2026-08-01',
        'contract_type': 'W2',
        'margin': 18.8,
        'hours': 96.0,
        'incentive_amount': 4200,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Referral',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Natalie Pereira',
        'coordinator_type': 'CRM',
        'candidate_id': 'CAND-NSK-4008',
        'candidate_name': 'Aarav Bhatt',
        'start_date': '2026-06-06',
        'month': '2026-08-01',
        'contract_type': 'FULLTIME',
        'margin': 8560.4,
        'hours': 1.0,
        'incentive_amount': 1000,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Internal DB',
        'team': 'Nashik CRM'},
    {   'coordinator_name': 'Priya Singh',
        'coordinator_type': 'Team Lead',
        'candidate_id': 'CAND-NSK-4009',
        'candidate_name': 'Ryan Bose',
        'start_date': '2026-07-12',
        'month': '2026-06-01',
        'contract_type': 'FULLTIME',
        'margin': 7663.9,
        'hours': 1.0,
        'incentive_amount': 4000,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Vendor',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Neha Sharma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-4010',
        'candidate_name': 'Ethan Bhatt',
        'start_date': '2026-01-20',
        'month': '2026-08-01',
        'contract_type': 'C2C',
        'margin': 8.5,
        'hours': 128.0,
        'incentive_amount': 1000,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Naukri',
        'team': 'Nashik Team Bravo'},
    {   'coordinator_name': 'Neha Sharma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-4011',
        'candidate_name': "Kabir D'Souza",
        'start_date': '2026-06-30',
        'month': '2026-06-01',
        'contract_type': 'W2',
        'margin': 11.2,
        'hours': 128.0,
        'incentive_amount': 1500,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Referral',
        'team': 'Nashik Team Bravo'},
    {   'coordinator_name': 'Priya Singh',
        'coordinator_type': 'Team Lead',
        'candidate_id': 'CAND-NSK-4012',
        'candidate_name': 'Dev Kapoor',
        'start_date': '2026-08-08',
        'month': '2026-08-01',
        'contract_type': 'C2C',
        'margin': 12.2,
        'hours': 128.0,
        'incentive_amount': 3500,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Referral',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-4013',
        'candidate_name': 'Isla Trivedi',
        'start_date': '2026-02-26',
        'month': '2026-07-01',
        'contract_type': 'W2',
        'margin': 9.1,
        'hours': 144.0,
        'incentive_amount': 3500,
        'incentive_type': 'RECURRING',
        'candidate_source': 'LinkedIn',
        'team': 'Nashik Management'},
    {   'coordinator_name': 'Neha Sharma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-4014',
        'candidate_name': "Ryan D'Souza",
        'start_date': '2026-06-09',
        'month': '2026-08-01',
        'contract_type': 'W2',
        'margin': 18.6,
        'hours': 152.0,
        'incentive_amount': 3500,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Vendor',
        'team': 'Nashik Team Bravo'},
    {   'coordinator_name': 'Priya Singh',
        'coordinator_type': 'Team Lead',
        'candidate_id': 'CAND-NSK-4015',
        'candidate_name': 'Olivia Patel',
        'start_date': '2026-03-08',
        'month': '2026-07-01',
        'contract_type': 'C2C',
        'margin': 8.2,
        'hours': 128.0,
        'incentive_amount': 2000,
        'incentive_type': 'ONE_TIME',
        'candidate_source': 'Referral',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Karan Johar',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-4016',
        'candidate_name': 'Liam Gupta',
        'start_date': '2026-01-05',
        'month': '2026-08-01',
        'contract_type': 'FULLTIME',
        'margin': 6312.5,
        'hours': 1.0,
        'incentive_amount': 500,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Naukri',
        'team': 'Nashik Team Charlie'},
    {   'coordinator_name': 'Rohan Verma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-4017',
        'candidate_name': 'Aditya Chatterjee',
        'start_date': '2026-02-21',
        'month': '2026-06-01',
        'contract_type': 'FULLTIME',
        'margin': 6914.3,
        'hours': 1.0,
        'incentive_amount': 500,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Naukri',
        'team': 'Nashik Team Alpha'},
    {   'coordinator_name': 'Neha Sharma',
        'coordinator_type': 'Recruiter',
        'candidate_id': 'CAND-NSK-4018',
        'candidate_name': 'Ryan Bose',
        'start_date': '2026-07-16',
        'month': '2026-07-01',
        'contract_type': 'W2',
        'margin': 14.1,
        'hours': 160.0,
        'incentive_amount': 2000,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Vendor',
        'team': 'Nashik Team Bravo'},
    {   'coordinator_name': 'Natalie Pereira',
        'coordinator_type': 'CRM',
        'candidate_id': 'CAND-NSK-4019',
        'candidate_name': 'Aditya Menon',
        'start_date': '2026-05-28',
        'month': '2026-08-01',
        'contract_type': 'C2C',
        'margin': 10.9,
        'hours': 160.0,
        'incentive_amount': 1500,
        'incentive_type': 'RECURRING',
        'candidate_source': 'Naukri',
        'team': 'Nashik CRM'},
    {   'coordinator_name': 'Monica Das',
        'coordinator_type': 'Manager',
        'candidate_id': 'CAND-NSK-4020',
        'candidate_name': 'Ava Trivedi',
        'start_date': '2026-07-26',
        'month': '2026-06-01',
        'contract_type': 'FULLTIME',
        'margin': 10695.8,
        'hours': 1.0,
        'incentive_amount': 3500,
        'incentive_type': 'FULL_TIME',
        'candidate_source': 'Internal DB',
        'team': 'Nashik Management'}]

def main() -> None:
    from sqlalchemy import text
    from sqlalchemy.orm import sessionmaker
    from app.core.db import get_engine, init_db

    init_db()

    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=get_engine())
    db = SessionLocal()
    try:
        version_id = db.execute(
            text(
                """
                INSERT INTO candidate_data_versions
                    (version_label, source_filename, division, row_count, notes)
                VALUES
                    (:label, :source, 'all', :row_count, 'Seeded from converted incentive report excel')
                RETURNING id
                """
            ),
            {
                "label": "converted-report-seed-all",
                "source": "Incentive_Report_Converted_All.xlsx",
                "row_count": len(RECORDS),
            }
        ).scalar()

        divisions = ["nashik", "sambhajiNagar", "ampcusTechClient", "ampcusTechInhouse"]
        for idx, rec in enumerate(RECORDS):
            rec["division"] = divisions[idx % len(divisions)]

        # One incentive cycle per distinct (month, division)
        cycle_keys = sorted(set((r["month"], r["division"]) for r in RECORDS))
        cycle_ids: dict[tuple[str, str], int] = {}
        for month, div in cycle_keys:
            year, mon, _ = month.split("-")
            incentive_month = f"{year}-{mon}"
            if int(mon) == 12:
                next_first = f"{int(year) + 1}-01-01"
            else:
                next_first = f"{year}-{int(mon) + 1:02d}-01"
            import datetime
            cycle_end = (datetime.date.fromisoformat(next_first) - datetime.timedelta(days=1)).isoformat()

            cycle_id = db.execute(
                text(
                    """
                    INSERT INTO incentive_cycles (
                        name, division, incentive_month, cycle_start_date, cycle_end_date,
                        remarks, status, candidate_version_id, approved_at
                    ) VALUES (
                        :name, :div, :incentive_month, :cycle_start, :cycle_end,
                        'Seeded from converted incentive report excel', 'APPROVED', :vid, NOW()
                    ) RETURNING id
                    """
                ),
                {
                    "name": f"{div} {incentive_month} Cycle",
                    "div": div,
                    "incentive_month": incentive_month,
                    "cycle_start": month,
                    "cycle_end": cycle_end,
                    "vid": version_id,
                }
            ).scalar()
            cycle_ids[(month, div)] = cycle_id

        for rec in RECORDS:
            crm_value = rec["coordinator_name"] if rec["coordinator_type"] == "CRM" else "N/A"
            margin_value = rec["margin"] if rec["margin"] is not None else 0

            candidate_id = db.execute(
                text(
                    """
                    INSERT INTO candidates (
                        external_candidate_id, candidate_name, normalized_name,
                        contract_type, margin, start_date, recruiter, team_lead, crm,
                        candidate_source, organization, division,
                        source_version_id, last_touched_version_id, is_active, incentive_active
                    ) VALUES (
                        :ext_id, :cname, :nname,
                        :contract_type, :margin, :start_date, :recruiter, :team_lead, :crm,
                        :candidate_source, :organization, :div,
                        :vid, :vid, true, true
                    ) RETURNING id
                    """
                ),
                {
                    "ext_id": rec["candidate_id"],
                    "cname": rec["candidate_name"],
                    "nname": rec["candidate_name"].lower(),
                    "contract_type": rec["contract_type"],
                    "margin": margin_value,
                    "start_date": rec["start_date"],
                    "recruiter": rec["coordinator_name"],
                    "team_lead": rec["team"],
                    "crm": crm_value,
                    "candidate_source": rec["candidate_source"],
                    "organization": "Bravens Inc",
                    "div": rec["division"],
                    "vid": version_id,
                }
            ).scalar()

            db.execute(
                text(
                    """
                    INSERT INTO incentive_lines (
                        cycle_id, candidate_id, candidate_name, role, person,
                        incentive_type, rule_applied, eligible, base_incentive,
                        pro_rata_factor, amount, hours, margin, reason, payment_status
                    ) VALUES (
                        :cycle_id, :candidate_id, :candidate_name, :role, :person,
                        :incentive_type, 'excel_import', true, :amount,
                        1, :amount, :hours, :margin, 'Seeded from converted incentive report excel', 'UNPAID'
                    )
                    """
                ),
                {
                    "cycle_id": cycle_ids[(rec["month"], rec["division"])],
                    "candidate_id": candidate_id,
                    "candidate_name": rec["candidate_name"],
                    "role": rec["coordinator_type"],
                    "person": rec["coordinator_name"],
                    "incentive_type": rec["incentive_type"],
                    "amount": rec["incentive_amount"],
                    "hours": rec["hours"],
                    "margin": margin_value,
                }
            )

        db.commit()
        print(f"Successfully seeded {len(RECORDS)} records from Incentive_Report_Converted_All.xlsx.")
    except Exception as e:
        db.rollback()
        print(f"Error seeding: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    main()
